(() => {
  'use strict';
  const App=window.InoxApp,{D,$,$$,state}=App;
  App.lesson={id:1,step:0};
  App.getLessonState=id=>{state.lessonState[id]||={interactions:{},assessed:false};return state.lessonState[id]};
  App.updateLessonPosition=()=>{state.lastLesson={id:App.lesson.id,step:App.lesson.step};App.save();App.renderResume()};
  App.openLesson=(id,step=0)=>{App.lesson={id,step:Math.min(Number(step)||0,App.lessonSteps[id]-1)};$('#lessonTitle').textContent=`第${String(id).padStart(2,'0')}讲 · ${D.courses[id-1][1]}`;App.renderLesson();App.openLayer('lessonStudio')};
  App.renderLesson=()=>{$('#lessonProgress').style.width=`${((App.lesson.step+1)/App.lessonSteps[App.lesson.id])*100}%`;$('#lessonMeta').textContent=`${App.lesson.step+1} / ${App.lessonSteps[App.lesson.id]} · 自动保存`;App.updateLessonPosition();App.lessonRenderers[App.lesson.id]();App.loadNotes()};
  App.lessonActions=(label='继续',can=false)=>`<div class="lesson-actions"><button class="ghost-btn" type="button" id="lessonPrev" ${App.lesson.step===0?'disabled':''}>上一步</button><small id="lessonHint">${can?'已完成本步，可以继续。':'完成本屏操作后继续。'}</small><button class="primary-btn" type="button" id="lessonNext" ${can?'':'disabled'}>${label}</button></div>`;
  App.bindLessonNav=(can,label='继续')=>{const prev=$('#lessonPrev'),next=$('#lessonNext');prev?.addEventListener('click',()=>{App.lesson.step--;App.renderLesson()});next?.addEventListener('click',()=>{if(next.disabled)return;if(label==='完成本讲')App.showCompletion();else{App.lesson.step++;App.renderLesson()}})};
  App.enableLessonNext=(message='已完成本步，可以继续。')=>{const btn=$('#lessonNext');if(btn)btn.disabled=false;if($('#lessonHint'))$('#lessonHint').textContent=message};
  App.assessTeach=(text,id)=>{const sets={1:[['定义',['10.5','1.2','定义']],['相对耐蚀',['相对','可能','不等于','也会']],['使用边界',['环境','介质','温度','表面','标准']]],2:[['不绝对承诺',['不能保证','不等于','相对']],['工况变量',['介质','温度','氯','盐','表面','缝隙']],['确认动作',['确认','评估','标准']]],3:[['组织分类',['奥氏体','铁素体','马氏体','双相','组织']],['反驳磁性分档',['不能','不足','不是']],['核验动作',['牌号','标准','检验']]]};const hits=sets[id].map(r=>[r[0],r[1].some(k=>text.includes(k))]),score=Math.round(hits.filter(x=>x[1]).length/hits.length*100);return `<div class="coach-result"><h3>${score>=70?'表达结构已建立':'还缺少关键环节'} · ${score}分</h3>${hits.map(x=>`<div class="rubric-line ${x[1]?'hit':'miss'}">${x[1]?'✓':'○'} ${x[0]}</div>`).join('')}<small>当前为本地规则评分；正式AI版将返回依据、遗漏和改写建议。</small></div>`};
  App.showCompletion=()=>{const id=App.lesson.id;if(!state.done.includes(id))state.done.push(id);state.lastLesson={id:Math.min(id+1,3),step:0};App.save();App.renderResume();App.renderCourses();const next=D.courses[id]?.[4]?id+1:null;$('#lessonBody').innerHTML=`<div class="lesson-screen"><div class="completion-card"><div class="completion-seal">完成</div><h1>第${String(id).padStart(2,'0')}讲已完成</h1><p>你已经完成情境判断、互动探索、证据阅读和表达输出。完成不等于永远记住，后续仍需通过间隔复习巩固。</p><div class="outcome-list" style="justify-content:center"><span>24小时复习</span><span>7天迁移题</span><span>30天工作案例</span></div><div class="completion-actions"><button class="ghost-btn" type="button" id="backHome">返回学习首页</button>${next?`<button class="primary-btn" type="button" id="nextLesson">进入第${String(next).padStart(2,'0')}讲</button>`:''}</div></div></div>`;$('#backHome').addEventListener('click',()=>{App.closeLayer('lessonStudio');App.switchView('home')});$('#nextLesson')?.addEventListener('click',()=>App.openLesson(next,0));App.toast('学习记录已保存')};
  App.initLessons=()=>{$$('[data-open-lesson]').forEach(b=>b.addEventListener('click',()=>App.openLesson(Number(b.dataset.openLesson),0)))};
})();