(() => {
  'use strict';
  const App=window.InoxApp,{D,$,$$}=App;
  App.lessonRenderers[3]=()=>{
    const root=$('#lessonBody'),ls=App.getLessonState(3),step=App.lesson.step;
    if(step===0){const answer=ls.interactions.sort,answered=Boolean(answer);root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">FAST SORT · 快速分型</span><h1>哪一类最符合这条定义？</h1><div class="claim-card"><blockquote>“基体兼有两相组织，其中较少相的含量至少为25%。”</blockquote><div class="evidence-buttons">${['奥氏体','双相','铁素体','马氏体'].map(x=>`<button type="button" class="${answer===x?'selected':''}" data-family-answer="${x}">${x}</button>`).join('')}</div></div><div>${answered?`<div class="feedback-panel"><p>${answer==='双相'?'正确。这是双相不锈钢定义中的关键条件。':'再看“两相组织”和“较少相至少25%”。'}</p></div>`:''}</div>${App.lessonActions('进入组织地图',answered)}</div>`;$$('[data-family-answer]',root).forEach(b=>b.addEventListener('click',()=>{ls.interactions.sort=b.dataset.familyAnswer;App.save();App.lessonRenderers[3]()}));App.bindLessonNav(answered,'进入组织地图');}
    if(step===1){const visited=ls.interactions.families||['austenitic'],enough=visited.length>=3;root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">MAP · 组织地图</span><h1>点击五类组织，抓住定义里的动词。</h1><p class="lead">至少查看三个家族，再继续判断磁性问题。</p><div class="family-tabs">${Object.keys(D.families).map(k=>`<button type="button" data-family="${k}" class="${(ls.interactions.activeFamily||'austenitic')===k?'active':''}">${D.families[k][0].replace('不锈钢','')}</button>`).join('')}</div><div class="family-panel" id="familyPanel"></div>${App.lessonActions('进入岗位判断',enough)}</div>`;const show=k=>{const f=D.families[k];ls.interactions.activeFamily=k;ls.interactions.families=[...new Set([...(ls.interactions.families||[]),k])];App.save();$('#familyPanel').innerHTML=`<div class="family-mark">${f[1]}</div><div><span class="eyebrow">${f[3]}</span><h2>${f[0]}</h2><p>${f[2]}</p></div>`;$$('[data-family]',root).forEach(x=>x.classList.toggle('active',x.dataset.family===k));if(ls.interactions.families.length>=3)App.enableLessonNext()};$$('[data-family]',root).forEach(b=>b.addEventListener('click',()=>show(b.dataset.family)));show(ls.interactions.activeFamily||'austenitic');App.bindLessonNav(ls.interactions.families.length>=3,'进入岗位判断');}
    if(step===2){const answer=ls.interactions.decision,answered=Boolean(answer);root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">DECISION · 岗位判断</span><h1>“带磁＝低档不锈钢”为什么站不住？</h1><p class="lead">请选择最稳健的回答。</p><div class="decision-options">${[['分类依据是组织与强化机制，磁性不是档次标签',1],['只有304才算真正不锈钢',0],['价格越高，磁性越弱',0]].map(x=>`<button type="button" class="decision-option ${answer===x[0]?(x[1]?'correct':'wrong'):''}" data-value="${x[0]}"><b>${x[0]}</b></button>`).join('')}<div>${answered?`<div class="feedback-panel"><p>${answer.startsWith('分类依据')?'正确。组织分类不是价格等级表。':'该说法没有标准定义依据。'}</p></div>`:''}</div></div>${App.lessonActions('完成专业解释',answered)}</div>`;$$('.decision-option',root).forEach(b=>b.addEventListener('click',()=>{ls.interactions.decision=b.dataset.value;App.save();App.lessonRenderers[3]()}));App.bindLessonNav(answered,'完成专业解释');}
    if(step===3){const assessed=Boolean(ls.assessed),text=ls.interactions.teachText||'';root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">OUTPUT · 专业解释</span><h1>用组织分类替代“好钢/差钢”的粗暴标签。</h1><div class="teachback"><textarea id="teachText" maxlength="260" placeholder="说明铁素体、马氏体、双相等类别，并解释为什么不能用磁性给材料分档。">${App.escapeHtml(text)}</textarea><div class="lesson-actions"><small id="charCount">${text.length} / 260</small><button class="primary-btn" type="button" id="assessTeach" ${text.length<40?'disabled':''}>提交给学习教练</button></div><div id="coachResult">${assessed?App.assessTeach(text,3):''}</div></div>${App.lessonActions('完成本讲',assessed)}</div>`;const ta=$('#teachText');ta.addEventListener('input',()=>{ls.interactions.teachText=ta.value;ls.assessed=false;App.save();$('#charCount').textContent=`${ta.value.length} / 260`;$('#assessTeach').disabled=ta.value.trim().length<40;$('#lessonNext').disabled=true});$('#assessTeach').addEventListener('click',()=>{ls.assessed=true;App.save();$('#coachResult').innerHTML=App.assessTeach(ta.value,3);App.enableLessonNext()});App.bindLessonNav(assessed,'完成本讲');}
  };
})();