(() => {
  'use strict';
  const App=window.InoxApp,{$,$$}=App;
  App.lessonRenderers[2]=()=>{
    const root=$('#lessonBody'),ls=App.getLessonState(2),step=App.lesson.step;
    if(step===0){const selected=ls.interactions.factors||[],correct=['介质与杂质','温度','pH','表面污染','结构缝隙','清洁维护'],enough=correct.filter(x=>selected.includes(x)).length>=4;root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">OBSERVE · 环境变量</span><h1>同样叫不锈钢，<br>为什么服役结果不同？</h1><p class="lead">点击真正可能影响腐蚀表现的因素。至少识别四项。</p><div class="select-tags">${[...correct,'宣传册颜色'].map(x=>`<button type="button" class="select-tag ${selected.includes(x)?'selected':''}" data-factor="${x}">${x}</button>`).join('')}</div><div>${selected.includes('宣传册颜色')?'<div class="feedback-panel"><p>宣传册颜色与本案例中的腐蚀表现无关。</p></div>':''}</div>${App.lessonActions('进入元素分工',enough)}</div>`;$$('[data-factor]',root).forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.factor;ls.interactions.factors=selected.includes(v)?selected.filter(x=>x!==v):[...selected,v];App.save();App.lessonRenderers[2]()}));App.bindLessonNav(enough,'进入元素分工');}
    if(step===1){const opened=ls.interactions.elements||[],enough=opened.length>=3;const cards=[['Cr','基本耐蚀性','并提高高温氧化抗力。','Outokumpu Handbook：铬是最重要的合金元素之一。',''],['Ni','促进奥氏体','通常提高塑性与韧性。','Outokumpu Handbook：镍主要促进奥氏体组织。','synthesis-card'],['Mo','提高局部腐蚀抗力','也要注意组织与制造边界。','Outokumpu Handbook：钼显著提高均匀和局部腐蚀抗力。','boundary-card']];root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">ELEMENTS · 元素分工</span><h1>Cr、Ni、Mo，做的不是同一件事。</h1><p class="lead">依次展开三张卡，区分基本耐蚀、组织稳定和局部腐蚀抗力。</p><div class="evidence-stack">${cards.map(x=>`<article class="evidence-card ${x[4]} ${opened.includes(x[0])?'open':''}" data-element="${x[0]}" tabindex="0"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><div class="more">${x[3]}</div></article>`).join('')}</div>${App.lessonActions('进入客户判断',enough)}</div>`;$$('.evidence-card',root).forEach(c=>{const toggle=()=>{c.classList.toggle('open');if(c.classList.contains('open'))ls.interactions.elements=[...new Set([...(ls.interactions.elements||[]),c.dataset.element])];App.save();if(ls.interactions.elements.length>=3)App.enableLessonNext()};c.addEventListener('click',toggle);c.addEventListener('keydown',e=>{if(e.key==='Enter')toggle()})});App.bindLessonNav(enough,'进入客户判断');}
    if(step===2){const answer=ls.interactions.decision,answered=Boolean(answer);root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">DECISION · 客户判断</span><h1>客户问：“316L是不是保证不生锈？”</h1><p class="lead">请选择最稳健、也最可执行的回答。</p><div class="decision-options">${[['是，316L等级高',0],['不能直接保证，需要确认工况',1],['直接换成更贵的牌号',0]].map(x=>`<button type="button" class="decision-option ${answer===x[0]?(x[1]?'correct':'wrong'):''}" data-value="${x[0]}"><b>${x[0]}</b></button>`).join('')}<div>${answered?`<div class="feedback-panel"><p>${answer==='不能直接保证，需要确认工况'?'正确。还需确认介质、温度、杂质、表面、结构和维护条件。':'牌号不能代替完整工况确认。'}</p></div>`:''}</div></div>${App.lessonActions('完成客户回应',answered)}</div>`;$$('.decision-option',root).forEach(b=>b.addEventListener('click',()=>{ls.interactions.decision=b.dataset.value;App.save();App.lessonRenderers[2]()}));App.bindLessonNav(answered,'完成客户回应');}
    if(step===3){const assessed=Boolean(ls.assessed),text=ls.interactions.teachText||'';root.innerHTML=`<div class="lesson-screen"><span class="eyebrow">OUTPUT · 客户回应</span><h1>用一句专业但不推诿的话回应客户。</h1><p class="lead">说明相对耐蚀性、工况变量和下一步确认动作。</p><div class="teachback"><textarea id="teachText" maxlength="260" placeholder="例如：316L通常具有更好的局部腐蚀抗力，但……">${App.escapeHtml(text)}</textarea><div class="lesson-actions"><small id="charCount">${text.length} / 260</small><button class="primary-btn" type="button" id="assessTeach" ${text.length<40?'disabled':''}>提交给学习教练</button></div><div id="coachResult">${assessed?App.assessTeach(text,2):''}</div></div>${App.lessonActions('完成本讲',assessed)}</div>`;const ta=$('#teachText');ta.addEventListener('input',()=>{ls.interactions.teachText=ta.value;ls.assessed=false;App.save();$('#charCount').textContent=`${ta.value.length} / 260`;$('#assessTeach').disabled=ta.value.trim().length<40;$('#lessonNext').disabled=true});$('#assessTeach').addEventListener('click',()=>{ls.assessed=true;App.save();$('#coachResult').innerHTML=App.assessTeach(ta.value,2);App.enableLessonNext()});App.bindLessonNav(assessed,'完成本讲');}
  };
})();